package TestCases;

import org.testng.annotations.Test;


import Object_Repository.Ultra_activations_Page;

import org.testng.annotations.BeforeMethod;
import org.openqa.selenium.By;
// import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
// import org.openqa.selenium.support.ui.Select;


public class Ultra_OrangeActivations_Test {
	public WebDriver driver;
	public WebDriverWait wait;
	Ultra_activations_Page hpp = new Ultra_activations_Page(driver);

	

  @BeforeMethod
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "//usr/local/bin/chromedriver");
	  driver = new ChromeDriver();
	  wait = new WebDriverWait(driver,10);
	  
  }
  
  
	 @Test (priority = 1)
	 public void ultraOrangeActivate_3Mo3Gb()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));  	  
	 }	
	 @Test (priority = 2)
	 public void ultraOrangeActivate_3Mo6Gb()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = 3)
	 public void ultraOrangeActivate_3MoUnli()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = 4)
	 public void ultraOrangeActivate_6Mo3Gb()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 @Test (priority = 5)
	 public void ultraOrangeActivate_6Mo6Gb()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 @Test (priority = 6)
	 public void ultraOrangeActivate_6MoUnli()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 @Test (priority = 7)
	 public void ultraOrangeActivate_12Mo3GB()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
	 }	
	 @Test (priority = 8)
	 public void ultraOrangeActivate_12Mo6GB()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = 9)
	 public void ultraOrangeActivate_12MoUnli()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 @Test (priority = 10)
	 public void ultraOrangeActivate_19()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_plan19_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_plan19_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 @Test (priority = 11)
	 public void ultraOrangeActivate_23()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_plan23_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_plan23_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = 12)
	 public void ultraOrangeActivate_29()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_plan29_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_plan29_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = 13)
	 public void ultraOrangeActivate_39()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_plan39_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_plan39_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 @Test (priority = -1)
	 public void ultraOrangeActivate_49()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONUltra())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(3000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_plan49_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_plan49_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 String substr = "";
		 substr = CopyActCode.substring(5,11);
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.ultramobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraHeader_button_Activate())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_image_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_textbox_ActCode())).sendKeys(CopyActCode);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  Thread.sleep(3000);
		  String GettingStartedText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_Activations_GettingStarted())).getText();
		  Assert.assertEquals(GettingStartedText, "Getting Started");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_Checkbox())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraBillingInto_Link_Skip())).click();
		  Thread.sleep(3000);  
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_FirstName())).sendKeys("Ultra");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_LastName())).sendKeys("Mobile");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Email())).sendKeys("noemail@ultra.me");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_UserName())).sendKeys("Test" + substr);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_Password())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultra_button_StartActivation())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.ultraActivation_text_Complete()));
		  
	 }	
	 
	 
	 @AfterMethod
  public void tearDown() {
		driver.quit();
  }

}
